# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4f3f05c2431614637838ec1448678900f15b7a94b34d915006a809dcd6e7245a95d7f0b71ac851dd0d27a10502487e35c3fd583074a6e4b2b862b802829093

test:
  secret_key_base: 0fe7d0ca4ca8ff352fe51cf5acda43ae1e382b56ed5e25b65edb94403b302cdb6ac6841a00a2296ed1ad22a6de79bcda97afcf04dc5d25e7732d057bb4374d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
